server:
  error:
    path: /error
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/folodb?user=folo&password=folo
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        jdbc:
          time_zone: Europe/Moscow
    generate-ddl: true
  liquibase:
    enabled: false
bot:
  username: ShurkaGurmanychBot
  token: 5306754558:AAGLFdpVE-VQJ3-Ym0uvLq5fbAU9q98cg-I
  path: https://7b27-2a02-2168-a97e-3700-71b9-a8b3-ab61-4222.eu.ngrok.io