server:
  error:
    path: /error
  tomcat:
    accesslog:
      enabled: true
    relaxed-query-chars: '|,{,},[,]'
    relaxed-path-chars: '|,{,},[,]'
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    net.bramp.ffmpeg: WARN
#    tomcat: OFF
#  group:
#    tomcat: org.apache.catalina, org.apache.coyote, org.apache.tomcat


spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/folodb?user=folo&password=folo
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        jdbc:
          time_zone: Europe/Moscow
    generate-ddl: true
  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog/changelog-master.yml'
  mustache:
    servlet:
      expose-request-attributes: true
bot:
  username: ShurkaGurmanychBot
  token: 5306754558:AAGLFdpVE-VQJ3-Ym0uvLq5fbAU9q98cg-I
  provider.token: 401643678:TEST:dfc5c1d7-9398-43aa-8df9-ae52cb992e12

openai:
  token: ${OPENAI_TOKEN}

ffmpeg:
  path: 'src/main/resources/ffmpeg/ffmpeg.exe'