/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.everbald.folobot.service.hh

import com.everbald.folobot.service.hh.model.VacanciesVacanciesResponse
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.RequestHeader
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestMethod
import org.springframework.web.bind.annotation.RequestParam
import java.math.BigDecimal

interface HHApi {
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/vacancies"],
            produces = ["application/json"]
    )
    fun getVacancies(
        @RequestHeader(value = "HH-User-Agent", required = true) hhUserAgent: String = "HH-User-Agent",
        @RequestParam(value = "page", required = false, defaultValue = "0") page: Int = 0,
        @RequestParam(value = "per_page", required = false, defaultValue = "10") perPage: Int = 10,
        @RequestParam(value = "text", required = false) text: String? = null,
        @RequestParam(value = "search_field", required = false) searchField: String? = null,
        @RequestParam(value = "experience", required = false) experience: String? = null,
        @RequestParam(value = "employment", required = false) employment: String? = null,
        @RequestParam(value = "schedule", required = false) schedule: String? = null,
        @RequestParam(value = "area", required = false) area: String? = null,
        @RequestParam(value = "metro", required = false) metro: String? = null,
        @RequestParam(value = "professional_role", required = false) professionalRole: String? = null,
        @RequestParam(value = "industry", required = false) industry: String? = null,
        @RequestParam(value = "employer_id", required = false) employerId: String? = null,
        @RequestParam(value = "currency", required = false) currency: String? = null,
        @RequestParam(value = "salary", required = false) salary: BigDecimal? = null,
        @RequestParam(value = "label", required = false) label: String? = null,
        @RequestParam(value = "only_with_salary", required = false) onlyWithSalary: Boolean? = null,
        @RequestParam(value = "period", required = false) period: BigDecimal? = null,
        @RequestParam(value = "date_from", required = false) dateFrom: String? = null,
        @RequestParam(value = "date_to", required = false) dateTo: String? = null,
        @RequestParam(value = "top_lat", required = false) topLat: BigDecimal? = null,
        @RequestParam(value = "bottom_lat", required = false) bottomLat: BigDecimal? = null,
        @RequestParam(value = "left_lng", required = false) leftLng: BigDecimal? = null,
        @RequestParam(value = "right_lng", required = false) rightLng: BigDecimal? = null,
        @RequestParam(value = "order_by", required = false) orderBy: String? = null,
        @RequestParam(value = "sort_point_lat", required = false) sortPointLat: Double? = null,
        @RequestParam(value = "sort_point_lng", required = false) sortPointLng: Double? = null,
        @RequestParam(value = "clusters", required = false) clusters: Boolean? = null,
        @RequestParam(value = "describe_arguments", required = false) describeArguments: Boolean? = null,
        @RequestParam(value = "no_magic", required = false) noMagic: Boolean? = null,
        @RequestParam(value = "premium", required = false) premium: Boolean? = null,
        @RequestParam(value = "responses_count_enabled", required = false) responsesCountEnabled: Boolean? = null,
        @RequestParam(value = "part_time", required = false) partTime: String? = null,
        @RequestParam(value = "accept_temporary", required = false) acceptTemporary: Boolean? = null,
        @RequestParam(value = "locale", required = false, defaultValue = "RU") locale: String = "RU",
        @RequestParam(value = "host", required = false, defaultValue = "hh.ru") host: String = "hh.ru"
    ): ResponseEntity<VacanciesVacanciesResponse>
}
